In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("sample_-_superstore.csv")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01/03/2023,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,01/05/2023,01/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,12/30/2026,01/03/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,12/30/2026,01/03/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,12/30/2026,01/03/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,12/30/2026,01/03/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,12/30/2026,01/03/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: float64(3), int64(2), object(16)
memory usage: 1.6+ MB

In [19]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [20]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,01/03/2023,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,01/04/2023,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,01/05/2023,01/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [21]:
df["Order Date"] = pd.to_datetime(df["Order Date"],errors = "coerce")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(15)
memory usage: 1.6+ MB

In [12]:
df.drop_duplicates(subset = "Order ID",inplace = True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5111 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          5111 non-null   int64
 1   Order ID        5111 non-null   object
 2   Order Date      5111 non-null   datetime64[ns]
 3   Ship Date       5111 non-null   object
 4   Ship Mode       5111 non-null   object
 5   Customer ID     5111 non-null   object
 6   Customer Name   5111 non-null   object
 7   Segment         5111 non-null   object
 8   Country/Region  5111 non-null   object
 9   City            5111 non-null   object
 10  State/Province  5111 non-null   object
 11  Postal Code     5111 non-null   int64
 12  Region          5111 non-null   object
 13  Product ID      5111 non-null   object
 14  Category        5111 non-null   object
 15  Sub-Category    5111 non-null   object
 16  Product Name    5111 non-null   object
 17  Sales           5111 non-null   float64
 18  Quantity        5111 non-null   int64
 19  Discount        5111 non-null   float64
 20  Profit          5111 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(3), object(14)
memory usage: 878.5+ KB

In [14]:
df.head(4)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,-9223372036854775808,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,-9223372036854775808,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,5,US-2023-141817,2023-01-05,01/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,-9223372036854775808,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840
5,6,US-2023-167199,2023-01-06,01/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,-9223372036854775808,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078

In [23]:
df["Postal Code"].unique()

array(['77095', '60540', '19143', '42420', '30605', '90049', '77340',
       '78041', '22153', '19901', '94109', '29464', '43055', '71111',
       '19140', '30076', '19134', '97477', '85254', '72401', '48185',
       '37167', '33180', 'M7A', '47905', '89115', '57701', '22304',
       '92037', '10024', '48234', '92691', '54302', '33710', '98105',
       '92025', '92024', '60441', '23320', '7036', '89031', '65203',
       '94521', '98103', '75220', '60653', '79424', '76017', '47374',
       '60098', '92553', '79907', '97504', '43229', '60126', '98115',
       '77036', '10035', '10009', '19120', '28403', '33063', '29203',
       '10701', '98198', '80219', '48073', '40475', '95661', 'T2C',
       '92646', '84321', '32216', '33614', '27604', '55044', '39212',
       '75217', '94110', '91505', '33801', '37918', '45011', '28806',
       '85705', '46368', '27405', '33445', '90036', '93727', '94122',
       '91767', '45503', '50315', '87105', '75023', '78521', '11561',
       '55124', '60610', '94591', '2151', '23464', '90008', '48205',
       '70506', '48127', '62521', '90004', '17602', '36608', '30062',
       '35601', '43615', '85301', '85224', '83501', '59405', '78745',
       '90278', '95240', '47401', '21215', '95123', '22204', '90045',
       '77070', '12180', '91776', '14701', '38109', '70601', '14609',
       '40214', '54915', '6457', '49201', '78207', '61032', '1841', 'M3C',
       '98031', '76106', '13601', '53209', '2038', '33012', '84084',
       '94601', '54703', '44312', '44105', '48640', '3820', '78666',
       'V6Z', 'H1A', '98006', '60623', '84107', '92105', '60089', '23223',
       '72209', '8701', '84057', '60505', '61604', '37620', '90032',
       '22801', '46544', '11550', '19711', 'B3H', '73505', '22980',
       '6450', '81001', '19013', '85023', '55407', '80027', '28027',
       '97301', '38671', '45231', '10011', '32725', '7060', '80013',
       '32137', '92020', '14215', '7601', '14304', '77573', '57103',
       '10801', '6010', '92503', '68104', '30318', '84020', '32712',
       '28205', '65807', '4401', '84062', '77590', '48183', '95687',
       'M5H', '30188', '33021', '6824', '75081', '31907', 'H1B', '23666',
       '44107', '63301', '33161', '49505', '11572', '59102', '42301',
       '33178', '87505', '72701', '43402', '74133', '60543', '95051',
       '99301', '75701', '31204', '1852', '43130', '48227', '27834',
       '97030', '7011', 'H1C', '93030', '66062', '27511', '45014',
       '79762', '85281', '78415', '91911', '90805', '21044', '61701',
       'M2N', '75043', '33433', '77041', '75150', '28314', '37042',
       '33437', '89502', '60201', '27707', 'T1Y', 'T5A', '46203', '28540',
       '95336', '91104', '98026', '10550', '2149', '3301', '44134',
       '77705', '36116', '71854', '90712', 'V6G', '23602', '91730',
       '29730', '33311', '67846', '47201', '2920', '44052', '85323',
       '45040', '7050', '97206', '44256', '75061', '37211', '54401',
       '96003', '19601', '53711', '75007', '77506', '37604', '66502',
       '56560', '75104', '60016', '53132', '84604', '19805', '84106',
       '55433', '71203', '60440', '95823', '63116', 'A0A', '2895',
       '94513', '13501', '97224', '11520', '60076', '32839', '20735',
       '30328', 'E1A', '73120', 'V6B', '85234', '98502', '85204', '83605',
       '43302', '35630', '38401', '75051', '80229', 'V5K', '77642',
       '80906', '1915', '92804', '60174', '44240', '55016', 'G1B',
       '48180', 'C0A', '2908', '77520', '55125', '60068', '38134',
       '59715', '33407', '13440', '23434', '53142', '8861', '71901',
       '88001', '48310', '1453', '16602', '75019', '18018', '47362',
       '33317', '95928', '84043', '36830', '92404', '93534', '35810',
       '91360', '29501', '98042', '33065', '33142', '61761', '48911',
       '99207', '6360', '68701', '87401', '78501', '47150', '93454',
       '32114', '20016', '45373', '60477', '75002', '44221', '93010',
       '27893', '60423', '67212', '76117', '6040', '7501', '83201',
       '4240', '85345', '84041', '30344', '30080', '60188', '1040',
       '8360', '79109', '93309', '34952', '60035', '46614', '39401',
       '63122', '83704', '97756', '55122', '92399', '2740', '41042',
       '18103', '92563', '76021', '49423', '22901', '55901', '33319',
       '92253', '92374', '13021', '29406', '48146', '2169', '92054',
       '37064', '52001', '74012', '61107', '37130', '7002', '2138',
       '62301', '97123', '20852', '31088', '48104', '93101', '46060',
       '48858', '60462', '89431', '93905', '72032', '28110', '05401',
       '46226', '55113', '59601', '37087', '87124', '75034', '7960',
       '38301', '92530', '33024', '61821', '48126', '92704', '32303',
       '92592', '92627', '60025', '86442', '11757', '54880', '43017',
       '93277', '59801', '20877', '98632', '7090', '39503', '8401',
       '85635', '37421', '7109', '54601', '78664', '1810', '6460',
       '78550', '94061', '77803', '2148', '80122', '63376', '73071',
       '76051', '28052', 'V6E', '65109', '92672', '92345', '89015',
       '24153', '85364', '6708', '2886', '7055', '80134', '80501',
       '17403', '48066', '80020', 'R0H', '42104', '32503', '37075',
       '53214', '70065', '95616', '78539', '80525', '78577', '53081',
       '80112', '76706', '53186', '40324', '52402', '55106', '27360',
       '60090', '95207', '80004', '83301', '92677', '1752', '98052',
       '95695', 'S0G', '52240', '46350', '92630', '33134', '75056',
       '98270', '77571', 'R3R', '8302', '93405', '77301', '50322',
       '97405', '82001', '60004', '98002', '98661', '27217', '88220',
       '73034', '90640', '6484', '7017', '66212', '28601', '76903',
       '52302', '95037', '42071', '94509', '75080', '68025', '46142',
       '33030', '90503', '92307', '27534', '3060', '77536', '35401',
       '32174', '76248', '35244', '74403', '72756', '33068', '94533',
       '48237', '8901', '80634', '34741', '32771', '61832', '92683',
       '76063', '58103', '20707', '98226', '77489', '77581', '48307',
       '55369', '27514', '80022', '26003', '95610', '90660', '94403',
       '50701', '46514', '80538', '90301', '91941', '95351', '64055',
       '88101', '68801', '32935', '71603', '56301', '33023', '44060',
       '83642', '94526', '72762', '94086', '92236', '57401', '33458',
       '94568', '43123', '44035', '21740', '48601', '77840', '91761',
       '98059', '48187', '29483', '64118', '90604', '79605', '52601',
       '60067', '60302', '32127', '6810', '98208'], dtype=object)

In [24]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717

In [25]:
df.drop(columns = "Product Name")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,State/Province,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,Texas,77095,Central,OFF-PA-10000174,Office Supplies,Paper,16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-BI-10004094,Office Supplies,Binders,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-LA-10003223,Office Supplies,Labels,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,Illinois,60540,Central,OFF-ST-10002743,Office Supplies,Storage,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,01/12/2023,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,Pennsylvania,19143,East,OFF-AR-10003478,Office Supplies,Art,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,2026-12-30,01/03/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,OFF-BI-10003684,Office Supplies,Binders,52.776,3,0.2,19.7910
10190,10191,US-2026-115427,2026-12-30,01/03/2027,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,California,94533,West,OFF-BI-10004632,Office Supplies,Binders,20.720,2,0.2,6.4750
10191,10192,US-2026-156720,2026-12-30,01/03/2027,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,Colorado,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,3.024,3,0.2,-0.6048
10192,10193,US-2026-143259,2026-12-30,01/03/2027,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,New York,10009,East,TEC-PH-10004774,Technology,Phones,90.930,7,0.0,2.7279
10193,10194,CA-2026-143500,2026-12-30,01/03/2027,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,Prince Edward Island,C0A,East,OFF-BI-10004040,Office Supplies,Binders,3.024,3,0.2,-0.6048

In [27]:
df["Order Date"] = pd.to_datetime(df["Order Date"],errors = "coerce")

In [28]:
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,01/07/2023,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,01/08/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717

In [29]:
df["Ship Date"] = pd.to_datetime(df["Ship Date"],errors = "coerce")

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(14)
memory usage: 1.6+ MB

In [31]:
df["Shipping Days"] = (df["Ship Date"]-df["Order Date"]).dt.days

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 22 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   Country/Region  10194 non-null  object
 9   City            10194 non-null  object
 10  State/Province  10194 non-null  object
 11  Postal Code     10194 non-null  object
 12  Region          10194 non-null  object
 13  Product ID      10194 non-null  object
 14  Category        10194 non-null  object
 15  Sub-Category    10194 non-null  object
 16  Product Name    10194 non-null  object
 17  Sales           10194 non-null  float64
 18  Quantity        10194 non-null  int64
 19  Discount        10194 non-null  float64
 20  Profit          10194 non-null  float64
 21  Shipping Days   10194 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(3), object(14)
memory usage: 1.7+ MB

In [52]:
df.drop(columns = "Product Name")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Sales,Quantity,Discount,Profit,Shipping Days
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,16.448,2,0.2,5.5512,4
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,3.540,2,0.8,-5.4870,4
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,11.784,3,0.2,4.2717,4
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,272.736,3,0.2,-64.7748,4
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,19.536,3,0.2,4.8840,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,OFF-BI-10003684,Office Supplies,Binders,52.776,3,0.2,19.7910,4
10190,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,94533,West,OFF-BI-10004632,Office Supplies,Binders,20.720,2,0.2,6.4750,4
10191,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,80538,West,OFF-FA-10003472,Office Supplies,Fasteners,3.024,3,0.2,-0.6048,4
10192,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,10009,East,TEC-PH-10004774,Technology,Phones,90.930,7,0.0,2.7279,4
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,C0A,East,OFF-BI-10004040,Office Supplies,Binders,3.024,3,0.2,-0.6048,4

In [53]:
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7

In [54]:
df["Country/Region"].unique()

array(['United States', 'Canada'], dtype=object)

In [55]:
df.groupby("Country/Region")["Sales"].mean()

Country/Region
Canada           146.667470
United States    229.858001
Name: Sales, dtype: float64

In [56]:
df.groupby("Country/Region")["Profit"].mean()

Country/Region
Canada           29.498965
United States    28.656896
Name: Profit, dtype: float64

In [57]:
df.groupby("Segment")["Sales"].mean()

Segment
Consumer       221.673885
Corporate      231.652471
Home Office    241.397933
Name: Sales, dtype: float64

In [58]:
df.groupby("Segment")["Profit"].mean()

Segment
Consumer       25.823035
Corporate      30.501502
Home Office    33.831996
Name: Profit, dtype: float64

In [59]:
df.groupby("Country/Region")["Order ID"].value_counts()

Country/Region  Order ID
Canada          CA-2023-131807    6
                CA-2026-131807    6
                CA-2023-115238    5
                CA-2023-151799    5
                CA-2024-115238    5
                                 ..
United States   US-2026-169607    1
                US-2026-169810    1
                US-2026-169817    1
                US-2026-169901    1
                US-2026-169929    1
Name: count, Length: 5111, dtype: int64

In [60]:
df.groupby("City")["Profit"].mean()

City
Aberdeen         6.630000
Abilene         -3.758400
Akron           -8.887410
Albuquerque     45.292007
Alexandria      19.913644
                  ...
Woonsocket      19.669775
Yonkers        184.517047
York           -20.433840
Yucaipa         13.208000
Yuma          -116.497725
Name: Profit, Length: 542, dtype: float64

In [61]:
round(df.groupby("Ship Mode")["Profit"].mean(),2)

Ship Mode
First Class       31.66
Same Day          29.54
Second Class      29.79
Standard Class    27.48
Name: Profit, dtype: float64

In [62]:
df.groupby("Category")["Sales"].mean()

Category
Furniture          342.911295
Office Supplies    119.434288
Technology         450.344922
Name: Sales, dtype: float64

In [64]:
df.to_csv(r"C:\Users\EKANKSH\OneDrive\Documents\cleanedsuperstore.csv",index = False )